// <auto-generated />
using System;
using FoodingApp.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodingApp.EfCore.Migrations
{
    [DbContext(typeof(FoodingAppDb))]
    partial class FoodingAppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("FoodingApp.Library.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasAlternateKey("PrimaryGroupId", "SubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Food_Categories", (string)null);
                });

            modelBuilder.Entity("FoodingApp.Library.Models.FoodItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("FoodingApp.Library.Models.PrimaryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("Category_Id");

                    b.HasAlternateKey("Name")
                        .HasName("Category_Name");

                    b.ToTable("Primary_Categories", (string)null);
                });

            modelBuilder.Entity("FoodingApp.Library.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Grams")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("NutriScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("QuantityInUnitValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Gram");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("modified_at")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("Pk_Recipe_Ingredients_Id");

                    b.ToTable("Recipe_Ingredients", (string)null);
                });

            modelBuilder.Entity("FoodingApp.Library.Models.RecipeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Kcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreparationMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("PreparationTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("modified_at")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("recipe_Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("FoodingApp.Library.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("SubCategory_Id");

                    b.HasAlternateKey("Name")
                        .HasName("SubCategory_Name");

                    b.ToTable("SubCategories", (string)null);
                });

            modelBuilder.Entity("RecipeIngredientRecipeModel", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientsId", "RecipeesId");

                    b.HasIndex("RecipeesId");

                    b.ToTable("RecipeIngredientRecipeModel");
                });

            modelBuilder.Entity("FoodingApp.Library.FoodCategory", b =>
                {
                    b.HasOne("FoodingApp.Library.Models.PrimaryCategory", "PrimaryGroup")
                        .WithMany()
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodingApp.Library.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryGroup");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("FoodingApp.Library.Models.FoodItemModel", b =>
                {
                    b.HasOne("FoodingApp.Library.FoodCategory", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FoodingApp.Library.Nutrition.Nutrients", "Nutrients", b1 =>
                        {
                            b1.Property<int>("FoodItemModelId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FoodItemModelId");

                            b1.ToTable("FoodItems");

                            b1.ToJson("Nutrients");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemModelId");

                            b1.OwnsOne("FoodingApp.Library.Nutrition.MacroNutrients", "Macros", b2 =>
                                {
                                    b2.Property<int>("NutrientsFoodItemModelId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("Alcohol")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Carbs")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Fat")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Fiber")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Protein")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("SaturatedFat")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Sugars")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Water")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.HasKey("NutrientsFoodItemModelId");

                                    b2.ToTable("FoodItems");

                                    b2.WithOwner()
                                        .HasForeignKey("NutrientsFoodItemModelId");
                                });

                            b1.OwnsOne("FoodingApp.Library.Nutrition.Minerals", "Minerals", b2 =>
                                {
                                    b2.Property<int>("NutrientsFoodItemModelId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("Calcium")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Chloride")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Copper")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<int>("Id")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("Iodine")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Iron")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Magnesium")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Manganese")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Phosphorus")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Potassium")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Selenium")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Sodium")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("Zinc")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.HasKey("NutrientsFoodItemModelId");

                                    b2.ToTable("FoodItems");

                                    b2.WithOwner()
                                        .HasForeignKey("NutrientsFoodItemModelId");
                                });

                            b1.OwnsOne("FoodingApp.Library.Nutrition.Vitamins", "Vitamins", b2 =>
                                {
                                    b2.Property<int>("NutrientsFoodItemModelId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("VitaminA")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB1")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB12")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB2")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB3")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB5")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB6")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB7")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminB9")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminC")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminD")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminE")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.Property<double>("VitaminK")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("REAL");

                                    b2.HasKey("NutrientsFoodItemModelId");

                                    b2.ToTable("FoodItems");

                                    b2.WithOwner()
                                        .HasForeignKey("NutrientsFoodItemModelId");
                                });

                            b1.Navigation("Macros")
                                .IsRequired();

                            b1.Navigation("Minerals")
                                .IsRequired();

                            b1.Navigation("Vitamins")
                                .IsRequired();
                        });

                    b.Navigation("Category");

                    b.Navigation("Nutrients")
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeIngredientRecipeModel", b =>
                {
                    b.HasOne("FoodingApp.Library.Models.RecipeIngredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodingApp.Library.Models.RecipeModel", null)
                        .WithMany()
                        .HasForeignKey("RecipeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodingApp.Library.FoodCategory", b =>
                {
                    b.Navigation("FoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
